# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3cb5ae0c063fb58a166cb02db1d998e95119796088d5d5e757e626bbfadcfb14293c1df2cdc31d9aeabdeb415fcd67bdad9a04788c868c200540c04d374a1506

test:
  secret_key_base: 26047df254f31b4f57607269f72ade55b3833854c3b507a1e412437f7695e29926500fac38ae7b5fe356092d6aca6c6cc36baf86a43c8dc51929678c49194fd8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
